

nonalc_flavor_dict = { 
	'bar spoon turmeric': ['earthy', 'bitter', 'musky', 'peppery'],'agave nectar': ['notes of honey', 'sweet'], 
	'agave syrup': ['notes of honey', 'sweet'], 'agave': ['sweetened'], 'almond syrup':['subtle almond notes'], 
	'apple cider': ['reminiscent of fall'], 'apple juice': ['lightly sweet but not apple-forward'],
	'apple purée': ['mild apple notes','comforting'], 'apricot & cardamom syrup': ['lightly spiced', 'fragrant'], 
	'apricot jam':['hearty apricot notes'],'apricot nectar':['fruity sweetness'],'bacon lardons': ['savory'], 
	'banana liqueur': ['banana laffy taffy-like flavor', 'artificially sweet'], 'basil': ['herbal', 'vaguely italian'], 
	'basil leaves':['herby'], 'beets and veg juice': ['tastes like if came from Whole Foods'],
	'bitter lemon': ['very citrusy', 'highly sour'],'black pepper': ['neutral spiced'], 'boiling water': ['comforting'],
	'brown sugar': ['molasses notes'], "'butter, melted'": ['rich'],'butter':['rich'], 'candy cane': ['pepperminty'], 'caramel': ['luxurious'],
	'caramelised onion chutney': ['if you put onion churtney in a drink you deserve what this tastes like'],
	'caramel syrup': ['sugary sweet'], 'cardamom pods': ['frangrant', 'aromatic'], 'carbonated water': ['bubbly', 'subtly bitter'],
	'cardamom': ['kind of cinnamon-like'], 'celery salt': ['parsley taste', 'salty', 'distinctive celery taste'],
	'cherry juice': ['tart', 'sour-sweet'],'cherry syrup': ['very sweet cherry flavor'], 'chocolate ice cream': ['creamy', 'cocoa notes'],
	'chocolate milk': ['chocolatey dairy taste'], 'chocolate spread': ['nutella flavor'], 'chocolate powder': ['cocoa'],
	'chocolate syrup': ['nostaligic Hershey\'s flavor'], 'chopped mango': ['tropical', 'fruity'], 
	'cinnamon': ['Christmas-y', 'aromatic'], 'cinnamon powder': ['Christmas-y', 'aromatic'], 'cloudy apple juice': ['natural apple taste'],
	'cloudy lemonade': ['lemonade but tastier'], 'clove crushed garlic': ['pungent'],
	'coconut cream': ['creamy', 'rich'], 'clove':['very aromatic', 'spiced', 'astringent'],'cloves':['reminiscent of chai', 'musky'],
	'cocoa powder': ['chocolatey'], 'coconut milk':['very subtle coconut'],'coconut water':['subtle coconut'],
	'coffee liqueur': ['espresso notes'], 'coffee': ['roasted coffeee flavor'], 'coriander seed syrup': ['nutty', 'almost lemony or citrus aftertaste'],
	'cranberry jelly':['reminiscent of Thranksgiving'],'cranberry juice': ['sour', 'bitter'],'cranberry sauce': ['Thanksgiving-like'],
	'cream of coconut': ['rich', 'creamy', 'light coconut taste'], 'cream': ['heavy dairy aspects'], 
	'cola': ['fizzy', 'familiar soft drink taste'], 'cracked black pepper': ['neutral peppercorn spice'],
	'cucumber water': ['light vegetable aftertaste', 'summery'], 'cup of filter coffee': ['nice coffee taste'],
	'dark chocolate ganache': ['rich chocolately taste'],'diet lemonade': ['light lemon taste'], 'diet tonic water': ['bitter', 'quanine flavor'],
	'distilled vinegar': ['strong puckering taste'], 'dark chocolate': ['bitter cocoa flavor'],
	'demerara sugar syrup': ['toffee flavor'], 'demerara sugar': ['toffee flavor'], 'diet cola': ['aspartame', 'coke soda'],
	'double cream': ['dairy flavor'], 'dragon fruit juice':['exotic','kiwi or pear-like'],'earl grey syrup':['comforting tea notes'],
	'edible gold and nutmeg': ['nutty', 'rounded sweetness and spice flavor'], 'ground nutmeg': ['nutty', 'rounded sweetness'], 
	'nutmeg': ['nutty', 'rounded sweetness'], 'egg white': ['frothy', 'silky'],'large egg whites': ['frothy', 'silky'], 'egg yolk':['eggy'],
	'egg':['eggy'],'eggs':['eggy'],'elderflower syrup':['delicate floral taste', 'almost musky', 'palate-clensing finish', 'reminiscent of lychee'],
	'elderflower':['delicate floral taste', 'almost musky', 'palate-clensing finish', 'reminiscent of lychee'],
	'espresso': ['dark, bitter coffee'], 'fresh ginger': ['spicy', 'sharp', 'pungent'],
	'fresh lemon juice': ['bright citrus', 'puckering', 'sour'],'fresh lime juice': ['bright citrus', 'puckering', 'sour'],
	'fresh milk':['dairy notes', 'creamy'], 'fresh orange juice': ['breakfasty', 'citrusy','acidic'],
	'fresh pineapple': ['tropical', 'bright'], 'frangelico': ['hazelnut with a hint of cocoa and vanilla'],
	'freshly brewed coffee': ['roasted coffee flavor'], 'fromage frais': ['creamy fresh cheese'], 
	'funkin sour mix':['tangy', 'lemon-lime'], 'garlic salt': ['savory salty notes'], 'ginger & lime syrup':['spicy and bright'],
	'schweppes slimline ginger ale': ['fizzy and bordering on medicinal', 'citrusy ginger notes'], 
	'ginger ale': ['citrusy ginger notes'],'ginger beer': ['strong gigner taste'],'ginger bitters': ['medicinal ginger taste'],
	'ginger juice': ['fresh ginger flavor'], 'ginger liqueur': ['medicinal strong ginger taste'],'ginger syrup': ['sweet candied ginger flavor'],
	'ginger': ['spicy', 'sharp', 'pungent'], 'gingerbread man biscuit': ['tastes like Christmas'], 'ground ginger': ['spicy'],
	'grape soda': ['purple cough syrup vibes'], 'drambuie': ['honey taste', 'herbal', 'pleasant spiced notes'], 'granulated sugar':['sweetened'],
	'grapefruit juice': ['bitter', 'very sour citrus flavor'],'grapefruit zest': ['sharp bitter citrus notes'],
	'grated nutmeg': ['nutty', 'rounded sweetness and spice flavor'], 
	'green juice': ['sweet vegetable flavor', 'fresh', 'minimal lawn-clipping taste'],
	'green tea': ['grassy', 'matcha-taste'], 'grenadine': ['sweet but tarte', 'pomegranite notes', 'light cherry flavor'], 
	'ground cinnamon': ['spiced', 'hints of clove'],'ground cloves': ['pungent spice taste', 'astringent'],
	'guava juice': ['tropical', 'notes of pear or strawberry'], 'hickory chips': ['smokey'], 
	'hot chocolate': ['comforting and warm chocolate taste'], 'homemade honey syrup':['caramely sweet taste'],
	'homemade spiced sugar syrup': ['aromatic sweet flavor'],'honey syrup': ['sweet honey tones'], 'hot milk': ['warm', 'dairy'],
	'hot water': ['warm'],'honey':['sweet honey tones'], 'horseradish': ['unavoidable spicy aftertaste'], 
	'horseradish sauce': ['peppery', 'spicy'],'ice cream': ['dairy'],'iced tea':['herbal tea notes'], 'infused with chilli':['hot peppery'],
	'jasmine tea': ['mellow flowery taste'],'lavender tea bag': ['floral', 'tastes like perfume'],'mince pies': ['spiced meat'],
	'mincemeat': ['Christmas-y'], 'spruce':['essence of pine trees'],'lemon iced tea':['tea with a hint of lemon'],
	'lemon juice':['sour', 'citrusy', 'bitter', 'bright'],'lemon sherbet':['tangy lemon flavor'], 'lemonade':['lemony but not agressively sour'],
	'lime juice':['citrusy  but not agressively sour'], 'maldon sea salt':['salty'],'mandarin juice':['sweet orange flavor'],
	'mango juice':['tropical','fruity'],'mango pureé':['sweet', 'tropical', 'fresh mango flavor'],'maple syrup':['sweet', 'maple notes'],
	'marmalade':['bitter orange notes'],'mascarpone':['creamy but mild cheese flavor'],'milk':['dairy'],
	'mint iced tea':['aromatic', 'light minty flavor'],'mint leaves':['bright notes', 'herbal', 'minty', 'cooling'],'mint liqueur':['pepperminty'],
	'mint sprig':['cool and subtle mint taste'],'mint':['bright notes', 'herbal', 'minty', 'cooling'],
	'monin pistachio syrup':['nutty','subtle sweetness'], 'olive brine':['salty','briney', 'astringent'],'olive':['salty'],'olives':['salty'],
	'orange extract':['bright', 'slighly artificial orange notes'],'orange juice':['citrusy','acidic'],
	'orange sugar syrup':['sweet orange flavor'],'orgeat syrup':['sweet notes of candied orange'],'packet dry stuffing mix':['Thanksgiving essence'],
	'papaya purée':['melon-like'],'passion fruit juice':['tart','fuity', 'aromatic', 'passion fruit notes'],
	'passion fruit syrup':['sweet','fuity', 'aromatic', 'passion fruit notes'],
	'passion fruit yellow syrup':['sweet','fuity', 'aromatic', 'passion fruit notes'], 'pickle vinegar':['dill pickle taste', 'puckering'],
	'pear puree':['fresh pear flavor'],'pepper':['neutral peppercorn spice'],'peppercorns':['spicy pepper flavor'],'peppermint stick':['pepperminty'],
	'pineapple chunks':['tropical', 'sweet', 'fruity'],'pineapple juice':['tropical', 'sweet', 'fruity'],
	'pink grapefruit juice':['bitter', 'sour', 'citrusy'],'pink lemonade':['citrusy', 'lemon flavor but not sharply sour'],
	'pomegranate juice':['tart'],'pomelo juice':['grapefruit-like taste but less bitter'],
	'pumpkin purée':['tastes like fall', 'notes of butternut squash or sweet potato'],'pumpkin':['tastes like fall'],
	'raspberry puree':['fruity', 'berry notes'],'raw apple cider vinegar':['bright', 'puckeringly sour'],'rose syrup':['floral', 'sweet', 'frangrant'],
	'rose water':['floral', 'sweet', 'frangrant'],'rosemary':['herbal', 'pungent', 'piney'],'runny honey':['sweet honey tones'],
	'salt and black pepper':['lightly salted and peppered'],'salt and pepper':['lightly salted and peppered'], 'sage leaves': ['herbal'],
	'salt water':['tastes like the ocean'],'single cream':['cramy','dairy'],'smoked salt':['smokey', 'salty'],'soda water or champagne':['bubbly'],
	'soda water':['bubbly', 'light mineral taste'],'soda':['bubbly'],'sour mix':['sour', 'lemon-lime'],'sour syrup':['sour', 'lemon-lime'],
	'soy sauce':['salty', 'stir-fry vibes'],'sparkling apple juice':['bubbly', 'mild apple notes'],'sparkling apple soda':['bubbly', 'mild apple notes'],
	'sparkling water':['bubbly'],'split vanilla pod':['natural vanilla flavor'],'schweppes ginger ale':['mild ginger flavor'], 
	'star anise':['licorice flavor'], 'streaky bacon':['savory'],"'strong coffee, chilled'":['strong coffee taste'],'sugar or maple syrup':['sweet'],
	'sugar syrup':['sweet'],'sugar':['sweet'],'sweet beetroot juice':['earthy'], 'schweppes bitter lemon':['sour', 'bubbly', 'citrusy'],
	'schweppes lemonade':['bubbly', 'lemony but not agressively sour'],
	'schweppes slimline elderflower tonic':['bubbly', 'lightly floral', 'subtle mineral taste'],
	'schweppes slimline lemonade':['bubbly', 'lemony but not agressively sour'],'schweppes slimline tonic':['bitter', 'bubbly'],
	'schweppes soda water':['bubbly'],'schweppes tonic water':['bitter', 'bubbly'],
	'tabasco or worcestershire sauce':['savory', 'vinegar notes'],'tabasco sauce':['vinegar notes', 'spicy'],'tomato juice':['tastes like v8'],
	'tomato puree':['canned tomato taste'],'tonic water':['bubbly', 'bitter'],'tonic':['bubbly', 'bitter'],'turkey skin':['fatty', 'savory'],
	'unsalted butter':['rich'],'vanilla cream':['vanilla notes', 'creamy'],'vanilla extract':['vanilla notes'],
	'vanilla ice cream':['milky', 'vanilla notes'],'vanilla syrup':['sweet', 'vanilla notes'],'violet spray':['lightly floral'],'wasabi':['spicy that hits you in the back of the throat'],
	'watermelon juice':['summery', 'fruity', 'sweet'],'watermelon':['summery', 'melon notes', 'sweet'],'white caster sugar':['sweet'],
	'white granulated sugar':['sweet'],'white grape juice':['refreshing', 'light fruity taste'],'white pepper':['lightly slicy'],
	'white sugar cube':['sweet'],'whole milk':['dairy'],'worcestershire sauce':['savory', 'vinegar notes']}

#hand labled by googling "what does x taste like" since these aren't brand specific
specific_alcohols = {'absinthe': ['anise, fennel, and licorice notes', 'extremely alcoholic tasting'], 'asperol': ['blood orange-flavor'], 
'benedictine': ['sweet honey','holiday spices', 'notes of stone fruit', 'herbal nuance'], 'blue curaçao liqueur': ['bitter orange-flavor'],
'crème fraîche or cream': ['bright cream taste'], 'créme de cacao liqueur':['creamy chocolate taste'],'crème de cacao':['creamy chocolate taste'],
'crème de cassis': ['black currant', 'almost wine-like'],'crème de framboise':['fresh raspberry taste'],'créme de mure':['dark blackberry taste'],
'créme de violette':['flowery', 'sweet', 'perfume-y taste'],'dark créme de cacao': ['dark cocoa liquor taste'], 
'elderflower cordial':['delicate floral taste', 'almost musky', 'palate-clensing finish', 'reminiscent of lychee'], 
'schweppes blackcurrant cordial': ['somewhat wine-like', 'berry or fruity notes'], 'lillet blanc': ['fruity', 'not overly sweet'],
'amaretto liqueur':['distinct almond flavor', 'cherry undertones'],'amaretto':['distinct almond flavor', 'cherry undertones'],
'calvados':['reminiscent of apples and pears', 'aged flavor'],
'campari':['bitter', ' notes of sweet cherry and orange', 'spicy edge reminiscent of cinnamon'],
'maraschino liqueur':['dry', 'subtle bitter almond flavor'], 'orange liqueur':['crisp', 'smooth', 'orange flavoured'], 
'peach schnapps':['peachy', 'fruity sweetness'], 'raspberry liqueur':['berry notes', 'true raspberry taste'], 
'southern comfort':['whiskey-like but easier to drink', 'apricot notes'],'triple sec':['subtle orange notes'], 
'vanilla liqueur':['upfront vanilla flavor'], 'white créme de cacao liqueur':['primarily chocolate fllavor with slight vanilla essence'],
'white crème de cacao':['primarily chocolate fllavor with slight vanilla essence'], 
'white chocolate liqueur':['cocoa butter aroma', 'subtley milky and vanilla-like'], 
'limoncello':['creamy lemon flavor'], 'sparkling wine':['bubbly', 'dry', 'subtle fruit notes'] }

#these things I decided wouldn't impact taste if they sit on top of a drink
#should probabably check whole fruits to see if they're in smoothies and actually impact taste but I don't want to
tasteless_garnishes = ['apple', 'apricot', 'asparagus shoots to garnish', 'banana', 'basil garnish', 'berries', 'black cherries', 'blackberries', 
"'blueberries, blackberries and raspberries'",'blueberries', 'brandied cherry', 'brussel sprouts', 'celery stick','celery', 'cherry to garnish',
'cherry tomatoes','cherry', 'chocolate popping candy','chocolate shaving','chocolate shavings','chocolate sprinkles','chocolate sauce',
'chocolate-coated coffee bean','chopped strawberries', 'cherries', 'chocolate brownie','cinnamon stick','cracked chocolate','cranberries',
'crushed biscuit','cucumber slice','cucumber slices','cucumber', 'dark chocolate at least 75% cocoa', 'fresh chopped strawberries','fresh peach',
'garnish with cooked beetroot or candied beetroot', 'coffee bean', 'food colouring','garnish with pea shoots and mint', 'strawberry',
'garnish with raspberry dipped in edible glitter/ gold', 'grape','green apple','green pepper','ground almonds','hundreds-and-thousands','ice',
'gummy worms sweets', 'kiwi','large thin lemon zest','lavender stalk', 'lavender', 'lemon peel', 'lemon to garnish', 'pomegranate seeds',
'lemon twist and mint sprig to garnish','lemon wedge','lemon wheel','lemon zest','lemon', 'lime peel spiral','lime slice','lime twist','lime wedge',
'lime wheel','lime', 'sprig of dill', 'red grape','red pepper','raspberry', 'strawberry for garnish', 'rose petal','stalk of celery', 
'strawberries', 'sprinkles', 'sweet violets', 'maraschino cherry', 'macaroon', 'marigold flower', 'optional chocolate flakes to garnish', 'orange peel',
'orange slice', 'orange twist','orange wedge','orange zest',"'orange, sliced'",'orange','orchid','oreo cookies', 'passion fruit','pea shoots', 
'purple berries','raspberries to garnish','raspberries', 'mint to garnish', 'peach', 'pineapple', 'sweet oat biscuits', 'water' ,'whipped cream']

#these are things we should try and find general reviews taste words for and then apply to specific things below to cut down on work
general_alcohols = ['brandy', 'baileys', 'whiskey', 'whisky', 'gin', 'vodka', 'rum', 'tequila', 'vermouth', 'sherry', 'bitters']

#these we may need to find specific reviews of the exact product
unlabled = [
'angostura aromatic bitters', #have it from review code
'angostura bitters', #have it from review code
'angostura', #same as one above ^
'peychaud\'s bitters', #have it from review code
'orange bitters', #have two reviews from code
'apricot brandy',
'archers® peach schnapps',
'aromatic bitters',
'baileys almande (0.8 units)',
'baileys original (0.8 units)',
'baileys® chocolat luxe',
'baileys® coffee irish cream liqueur',
'baileys® orange truffle',
'baileys® original irish cream liqueur',
'baileys® original irish cream',
'baileys® pumpkin spice',
'baileys®',
'bell\'s® original blended scotch whisky',
'bergamot bitters','berry cordial',
'bitters',
'black walnut bitters',
'blackberry cordial',
'blossom hill sun-kissed red',
'blossom hill sun-kissed white',
'brandy',
'brut champagne',
'bulleit® bourbon',
'captain morgan original spiced gold',
'captain morgan® original rum',
'captain morgan® original spiced rum',
'captain morgan® white rum',
'cardhu® 12 year old','caster sugar',
'champagne',
'cherry brandy',
'chocolate bitters',
'chocolate liqueur',
'cîroc® vodka',
'clove bitters',
'coffee bitters',
'cognac',
'don julio® blanco tequila',
'don julio® reposado tequila',
'dry vermouth',
'dublin porter guinness', 
'fernet branca',
'fino sherry',
'french raspberry liqueur',
'gordon\'s® crisp cucumber gin',
'gordon\'s® london dry gin',
'gordon\'s® sloe gin','gordon\'s® with a spot of elderflower',
'gordon’s london dry gin','gordon’s premium pink gin (2 units)',
'guiness®',
'guinness',
'guinness® draught in a can',
'haig club™',
'j&b rare® blended scotch whisky',
'jeremiah weed® root brew',
'jeremiah weed® sour mash',
'johnnie walker black',
'johnnie walker® black label® blended scotch whisky',
'johnnie walker® blue label® blended scotch whisky',
'johnnie walker® double black label® blended scotch whisky',
'johnnie walker® gold label reserve',
'johnnie walker® platinum blended scotch whisky',
'johnnie walker® red label® blended scotch whisky',
'ketel one citroen® flavored vodka',
'ketel one® vodka',
'lagavulin® 16 year old',
'mahiki® coconut',
'martini rosso',
'oban little bay™ single malt',
'original bitters',
'pale ale',
'pampero blanco rum',
'pampero® especial rum',
'parrot bay® coconut',
'parrot bay® passion fruit',
'parrot bay® strawberry',
'peach bitters',
'pear oak bitters', 
'pedro ximenez -sherry-',
'pimento dram',
'pimm\'s no. 1®',
'pimm\'s® blackberry & elderflower',
'pimm\'s® cider cup',
'pimm’s® strawberry with a hint of mint',
'premium lager',
'prosecco',
'red vermouth',
'ron zacapa centenario',
'ruby port',
'smirnoff ice® flavored malt beverage',
'smirnoff no. 21® vodka',
'smirnoff peppermint twist',
'smirnoff® blueberry flavoured vodka',
'smirnoff® espresso flavoured vodka',
'smirnoff® gold',
'smirnoff® green apple flavoured vodka',
'smirnoff® lime flavoured vodka',
'smirnoff® vanilla flavoured vodka',
'sauvignon blanc',
'sherry',
'talisker skye','talisker® 10 year old',
'talisker® storm malt whisky',
'tanqueray london dry gin (2 units)',
'tanqueray london dry gin',
'tanqueray no. ten® gin',
'tanqueray® london dry gin',
'tawny port',
'the singleton® single malt',
'sweet vermouth',
'unpeated whiskey',
'vermouth', 
'vermouth rosso']

#this is the printout from the taste_profiles.py file
review_dict: {'tequila': ['special', 'frozen', 'delightful', 'less', 'mixed', 'crisp', 'perfect', 'woody', 'treat', 'aged'], 
'vodka': ['smooth', 'whipped', 'frozen', 'flavored'], 
'rum': ['caramel', 'mixed'], 
'Fee Brothers Cherry Cocktail Bitters ': ['perfect'], 
'Angostura Aromatic Bitters': ['tasty', 'sour', 'small', 'off'], 
'Woodford Reserve Spiced Cherry Bourbon Barrel Aged Cocktail Bitters ': ['mixed', 'terrific'], 
'Urban Moonshine ': ['organic'], 

'Peychauds Aromatic Cocktail Bitters ': ['muted', 'lemon', 'whole', 'bitter', 'caramel', 'sophisticated', 'vanilla', 'classic', 
'perfect', 'distinct', 'sweet', 'dusty', 'calorie', 'low'], 

'. Angostura Aromatic Bitters Cocktail Flavoring Bar Mixer': ['fantastic'], 
'Bittermens Xocolatl Mole Cocktail Bitters ': ['bloody', 'foul', 'whole', 'off', 'full', 'flavored', 'wonderful', 
'tender', 'tasty', 'fantastic', 'subtle', 'rich', 'plain', 'crafted', 'small', 'brown', 'lemon', 'tough', 'half', 'less', 
'mixed', 'warm', 'spiced', 'strong', 'large', 'aromatic', 'chocolate', 'honey', 'traditional', 'nutmeg', 'flavorful', 'choice', 
'sweet', 'intense', 'fresh', 'sharp', 'low', 'fruity', 'sour', 'delicious', 'citrus', 'complex', 'tart', 'bitter', 'distinctive', 
'vanilla', 'perfect', 'yummy', 'sauteed', 'hot', 'refreshing', 'appealing', 'spicy', 'golden', 'strange'], 

"Regan's Orange Bitters No. 6 ": ['citrus', 'boring', 'complex', 'bitter', 'wonderful', 'mixed', 'overpowering', 'potent', 'classic',
 'perfect', 'vanilla', 'flavorful', 'citrusy', 'strong', 'sweet', 'aromatic', 'intense', 'plain', 'spicy'], 

'Angostura Orange Bitters': ['delicate', 'tart', 'bitter', 'off', 'zesty', 'flavorless', 'less', 'classic', 'strong', 'carbonated',
 'sweet', 'aromatic', 'sharp', 'traditional']}


print("hand-labled this many:", len(nonalc_flavor_dict)+ len(specific_alcohols))
print("alcohols that need taste profiles:", len(unlabled))
print("all ingreds present in this file:", len(nonalc_flavor_dict)+ len(specific_alcohols)+ len(unlabled)+len(tasteless_garnishes))


#for key in nonalc_flavor_dict:
	#if nonalc_flavor_dict[key] == ['']:
		#print("if this prints this ingredient is not taste profiled:", key)

